version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
    - HOST=$nombre
    - USER=$usuario
    - PASSWORD=$contrasena
  mydb:
    image: postgres:10
    environment:
      - POSTGRES_DB=$postgresdb
      - POSTGRES_PASSWORD=$postgrespw
      - POSTGRES_USER=$postgresuser
